#!/usr/bin/env bash

# This generates a few of the test cases, the others are hand-generated by unknown means.

PPATH=$(realpath ..)
USE_ACM=1
. gen.sh

use_solution twosat_sl.cpp

ulimit -s unlimited

compile gen_random.py

sample 1

tc 30-small1         gen_random n=5 m=5 probs=0.1,0.2,0.3
tc 31-small2         gen_random n=10 m=10 probs=0.1,0.2,0.3
tc 32-small3         gen_random n=10 m=10 probs=0.1,0.2,0.3

tc 33-duplicates     gen_random n=10 m=100000 probs=0.1,0.2,0.3

tc 34-dense          gen_random n=1000 m=100000 probs=0.1,0.2,0.3

tc 35-rand1          gen_random n=100000 m=100000 probs=0.1,0.2,0.3
tc 36-rand2          gen_random n=100000 m=100000 probs=0.05,0.3,0.35

tc 37-only-x         gen_random n=100000 m=100000 probs=1,0,0
tc 38-only-min       gen_random n=100000 m=100000 probs=0,1,0
tc 39-only-eq        gen_random n=100000 m=100000 probs=0,0,1
tc 40-only-plus      gen_random n=100000 m=100000 probs=0,0,0

tc 41-mostly-eq      gen_random n=100000 m=100000 probs=0.05,0,0.9
tc 42-mostly-eq-nopm gen_random n=100000 m=100000 probs=0.05,0,0.95
tc 43-plus-minus     gen_random n=100000 m=100000 probs=0.02,0.49,0
